name: Release Beta
run-name: Release Beta ${{ inputs.version }} ${{ github.actor }} ${{ github.event_name }}

on:
  workflow_dispatch:

jobs:
  get-configs:
    uses: ./.github/workflows/configs.yml

  promote-main-to-beta:
    needs: [get-configs]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.version-and-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: 'main'
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js ${{ needs.get-configs.outputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.get-configs.outputs.node-version }}
          cache: 'npm'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version and Tag
        id: version-and-tag
        run: |
          PKG_VERSION=$(jq -r .version package.json)

          FULL_TAG="v${PKG_VERSION}-beta"
          git tag "$FULL_TAG"
          git push origin "$FULL_TAG"
          echo "Created tag from branch=$(git rev-parse --abbrev-ref HEAD), commit=$(git rev-parse HEAD), tag=$(git describe --tags --exact-match)"

          echo "tag=$FULL_TAG" >> $GITHUB_OUTPUT

  call-release:
    needs: [promote-main-to-beta]
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
    with:
      tag: ${{ needs.promote-main-to-beta.outputs.tag }}
