name: Pull Request

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [ main ]

jobs:
  get-configs:
    uses: ./.github/workflows/configs.yml

  pr-build-test-nodejs:
    needs: [ get-configs ]
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js ${{ needs.get-configs.outputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.get-configs.outputs.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Code Quality
        if: runner.os != 'Windows'
        run: npm run lint && npm run check:duplicates

      - name: Test
        run: npm run test

  pr-build-test-go:
    needs: [ get-configs ]
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go ${{ needs.get-configs.outputs.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.get-configs.outputs.go-version }}
          cache: true

      - name: Build
        shell: bash
        run: GOPROXY=direct go build -C ./cfn-init ./...

      - name: Test
        shell: bash
        run: GOPROXY=direct go test -C ./cfn-init -v -cover ./...
