name: Promote to Prod

on:
  workflow_dispatch:
    inputs:
      confirm_prod_promotion:
        description: 'Confirm promotion to PROD'
        required: true
        type: choice
        options:
        - 'No'
        - 'Yes'
        default: 'No'

permissions:
  contents: write

jobs:
  promote-to-prod:
    name: Promote Beta to Prod
    if: github.event.inputs.confirm_prod_promotion == 'Yes'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          
      - name: Merge beta into prod
        run: |
          git checkout beta
          git pull origin beta
          git checkout prod
          git pull origin prod
          git merge --no-ff -m "Release: Promoting beta to production" beta
          git push origin prod
